services:
  nginx:
    ports:
      - "80:80"
  api:
    build:
      context: .
      target: production
    ports:
      - 3000:3000
  db:
    image: bitnami/postgresql:latest
    ports:
      - '5434:5434'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: toolsdb
volumes:
  tools_pg_data: